### ISSUE TITLE
Finished first script week2 assignment

### ISSUE THREAD

**Issue by ldunne-matc** [madisoncollege-it-programs/python-scripting-ldunne-matc#1]
Check week2

**Comment by cethenmc** [comment]
Hi, Logan.  Please use a more descriptive variable name, as the recorded lectures and slide notes showed.

I would also like you to update your script so you can run it from the command line.

Your first line should always be the following for your scripts. In this way, if you are running from the command line it will know what interpreter to use. Will you please add this line to the top of your first-script.py code?

#!/usr/bin/env python3

Recall from the videos, you may also need to issue a chmod command to modify the rights to make it executable.

chmod u+x first-script.py

After this, you can execute from the command line.

./first-script.py

Please be so kind as to resubmit it, so...
    1. modify the file in NetLab with the added line at the top.
    2. update the file to be executable.
    3. add the file to staging (git add .)
    4. commit the file to your local repo. (git commit -m "changes requested to run from command line")
    5. push to the git hub repository (git push)
    6. reply to this same issue, saying you have completed these steps

Thanks.

~Chris

**Comment by ldunne-matc** [comment]
I apologize, I did what you asked, however I received an error:

[cid:fe0aeb16-791b-4073-bd1e-e7a927a4800b]
Would it be possible for us to do a live meet to work this out?

Thanks,
Logan Dunne

________________________________

**Comment by cethenmc** [comment]
Certainly, Logan.  Please see if you can find a mutually agreeable time under Instructor Contact in Blackboard.  If none of those times work well, please let me know.

Perhaps we can find a mutually agreeable time tomorrow.  My best opening opportunity is probably 2:30 PM tomorrow (even though that is not open on my calendar, I could likely make that work).

Thanks.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by cethenmc** [comment]
Logan.  I do see that you have us booked for Friday.  That is great.  Please don't let this one issue is not stopping you from progressing with the week 3 and week 4 labs.  I only ask because I have not seen week 3 turned in yet.  Thanks. ~Chris

**Comment by cethenmc** [comment]
Hi, Logan.  Please use a more meaningful variable name in the future.  Full score credited in gradebook.

**Comment by cethenmc** [comment]
Hi, Logan.  I have not seen a booking from you as of yet (Blackboard > Instructor Contact).  I am happy to help, so if you cannot make one of those openings work tomorrow, please let me know.  Hopefully, we can find another mutually agreeable time.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by ldunne-matc** [comment]
Hello Mr. Ethen,

Are you sure you do not see a booking? I will try to book another appointment. for Friday if possible.
________________________________
