### ISSUE TITLE
Week 3 assignment is done

### ISSUE THREAD

**Issue by ldunne-matc** [madisoncollege-it-programs/python-scripting-ldunne-matc#3]

**Comment by cethenmc** [comment]
I do not see a file named strings.py.  You must follow instructions.  If 'String Formatting.py' is your file name for the assignment, will you please resubmit it with the correct name?  Please make sure it is executable at the command line, as well.  Please reach out if any of this does not make sense, and I'd be happy to help.
Thanks.  ~Chris

**Comment by cethenmc** [comment]
Logan.  Still getting this for week3.  Note cstrings.py is mine, and not yours.  Please correct absolutely no later than Sunday night.

![image](https://user-images.githubusercontent.com/112707666/199645955-f7df3177-6d92-40b6-a8da-595f71619a79.png)

**Comment by ldunne-matc** [comment]
It should be changed now!

**Comment by cethenmc** [comment]
Logan - You are still printing out Blue 10 times in your variable.  Also, unsure why you added a single space at the front of each formatted string.  If you are curious, on the Blue, you could have just done varBlue * 10.  Recording 7 of 8.
