### ISSUE TITLE
Finished Week 4

### ISSUE THREAD

**Issue by ldunne-matc** [madisoncollege-it-programs/python-scripting-ldunne-matc#4]

**Comment by cethenmc** [comment]
Logan - Are you sure this is ready?  I don't see a sequences.py file, and there is no other file that is executable at the command line.  Please reach out if you have difficulties.  Thanks. ~Chris

**Comment by ldunne-matc** [comment]
Hi Chris,

Thank you. Do you see the files now?

I used:
Git add .
git commit -m "message"
git push origin main

Thanks,

Logan Dunne
________________________________

**Comment by cethenmc** [comment]
We are a step closer, Logan.  I see the files, but none are executable.

Remember these instructions from Week 2 (indented below)?  Please do the same for all scripts.  Please test them by running them from the terminal before pushing them to the GitHub repository.  I should be able to grade them if I can run them from the command line.  I will close all GitHub Issue tickets that have a perfect score.  I will send a reply to others that need corrections.  Please keep an eye out.

Hi, Logan. Please use a more descriptive variable name, as the recorded lectures and slide notes showed.
I would also like you to update your script so you can run it from the command line.
Your first line should always be the following for your scripts. In this way, if you are running from the command line it will know what interpreter to use. Will you please add this line to the top of your first-script.py code?
#!/usr/bin/env python3
Recall from the videos, you may also need to issue a chmod command to modify the rights to make it executable.
chmod u+x first-script.py
After this, you can execute from the command line.
./first-script.py
Please be so kind as to resubmit it, so...
1. modify the file in NetLab with the added line at the top.
2. update the file to be executable.
3. add the file to staging (git add .)
4. commit the file to your local repo. (git commit -m "changes requested to run from command line")
5. push to the git hub repository (git push)
6. reply to this same issue, saying you have completed these steps
Thanks.
~Chris
Thanks.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by cethenmc** [comment]
Thank you, thank you!  Nice work on this week 4 assignment.

Although I still do not have an executable Week 3 assignment, week #4 is now graded.  You switched the order of problem #3 and #4, but I will assume an honest mistake on that one.  Your results were correct, but #4 was done before #3.
