### ISSUE TITLE
Week 6 assignments are done. I hope I got them right this time. :)

### ISSUE THREAD

**Issue by ldunne-matc** [madisoncollege-it-programs/python-scripting-ldunne-matc#6]

**Comment by cethenmc** [comment]
Please reply to this issue when you believe these are ready for regrading.

**Comment by cethenmc** [comment]
Logan - Thanks for meeting on Friday.  I still do not see Week 5 or 6 out here. Please git push everything after you add and commit to your local repository.  

drwxrwxr-x  7 student student 4096 Oct  3 11:05 ./
drwxrwxr-x 19 student student 4096 Sep 14 21:30 ../
drwxrwxr-x  8 student student 4096 Oct 17 12:27 .git/
-rw-rw-r--  1 student student   75 Sep 14 09:30 README.md
drwxrwxr-x  2 student student 4096 Sep 14 09:30 week1/
drwxrwxr-x  2 student student 4096 Sep 14 09:30 week2/
drwxrwxr-x  2 student student 4096 Oct  3 11:05 week3/
drwxrwxr-x  2 student student 4096 Oct  3 23:13 week4/

**Comment by ldunne-matc** [comment]
That's odd. I can see them, and I uploaded them. Did I miss something?

[cid:4d72686f-039a-4a01-af4c-25cff26ed1d5]
[cid:1f908f5e-8b95-4354-8d43-ba50ddce209b]
________________________________

**Comment by ldunne-matc** [comment]
Hi Mr. Ethen,

Do you see Week 5 and 6 and my midterms on github? If not, I will go back in and reconfigure.

Thanks,
Logan Dunne
________________________________

**Comment by cethenmc** [comment]
They do not show updates since 10/14.  No Midterm folder comes down.  Can you take a snapshot of your git tree if you think you have more?  Not sure how there could possibly be a disconnect.  I see everything you push here, and can extract time stamps.

You did not push them to GitHub.

***@***.***
Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by cethenmc** [comment]
I should have answered your question more specifically.  Yes, week5 and week6 are out there.  You would know this, as I had placed comments in those issue tickets.  Week5 still needs a correction from after we met on Friday, 10/14.

You have had no check-ins (github pushes) since that day.

**Comment by ldunne-matc** [comment]
Okay, thank you. I think I may have found the problem. I will upload a test file tonight and rewrite the midterm files, then post them tomorrow.

Thank you for being so patient with me throughout these github issues. I apologize for the inconvenience, and if this works I will record exactly what I did so this (hopefully) never happens again.

Here are the files and the test file I will upload.

[cid:5a93d823-20c1-452e-9bf1-5c82bf039553]


Thank you so much,

Logan Dunne
________________________________

**Comment by cethenmc** [comment]
I will be interested in hearing what you did to make the issue occur.  The only think I can think of is if you connected to a different GitHub account.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by ldunne-matc** [comment]
Hello Mr. Ethens,

I have just returned home from my trip, and I uploaded the midterms to the correct repository. As it turns out, the issue was not with my incorrect use of GitHub, but more of my own incompetence.

      This is the second time I am taking this class since I want to get a better grade and a better understanding about the topics at hand. As such, in GitHub there is a DIFFRENT repository from my previous class taught by a different Chris. This repository looks the exact same as the current one, and it also contains the midterm folder with nearly the exact same files. I believe that when I was struggling with GitHub, I checked the wrong repository and falsely believed the files to already be uploaded.

I sincerely apologize for this debacle, and I am making sure I mark the difference between the two classes with a new file to remind me.

Thank you again,

Logan Dunne
________________________________

**Comment by ldunne-matc** [comment]
I deleted the old midterm files and remade them, so they should be completely fresh and on the correct branch.
________________________________

**Comment by cethenmc** [comment]
This explanation makes total sense to me now.   Thanks for taking the time to let me know.

Chris

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cethenmc** [comment]
I don't think good explanations were ever resubmitted for week5.  
Week 6 - booleans.py - looks good.  8 out of 8
Week 6 - flowcontrol.py -   okay.  8 out of 8
