### ISSUE TITLE
Last github issues pushed yesterday, and Week 9 is done!

### ISSUE THREAD

**Issue by ldunne-matc** [madisoncollege-it-programs/python-scripting-ldunne-matc#9]

**Comment by cethenmc** [comment]
Hi, Logan.  Regarding the Week 9 Lab, I cannot grade it because I cannot run it.  Please correct, re-push to GitHub, and reply to this ticket when ready.

![image](https://user-images.githubusercontent.com/112707666/199645590-5eab532c-7c20-46d6-85cc-3cbe5c42b4a0.png)

![image](https://user-images.githubusercontent.com/112707666/199645623-ba5a2a8e-b06f-47b8-b80a-5a4df93cba74.png)

**Comment by cethenmc** [comment]
On a side note.  Please also complete the Issue Tickets on Week 3 and Week 5, as they still have issues.  Please book me if you don't understand what I explained in those issue tickets.

**Comment by ldunne-matc** [comment]
Interesting. It works for me.
![image](https://user-images.githubusercontent.com/98551249/200191446-24d6a58a-ed82-45a8-a41e-7aef8c0a58c9.png)

**Comment by ldunne-matc** [comment]
This is the only issue that has me stumped. I looked online a few days ago, but I found nothing about why this occurs. I can still run it fine.

**Comment by cethenmc** [comment]
Hi, Logan.  I believe the only way this works for you is if you are running from the triangular play button or you precede your command line command with python3 (e.g., 'python3 ./tempconversion.py' or 'python3 ./f2c.py').  The reason for this is you did not put the shebang line in each file, and Linux does not know what interpreter to use with the script.

I have recorded a 4 out of 8 for now.  You definitely want to resubmit with corrections for full credit.  The final will be full of functions.  The following unchecked boxes were unfulfilled requirements of the lab exercise.

![image](https://user-images.githubusercontent.com/112707666/202522798-734b39bf-a879-4487-9223-7871952fbbeb.png)

**Comment by cethenmc** [comment]
PS - I don't see a week 10 issue created.  However, looking at the repository, it looks like you checked in code for week 10.  Will you please create an Issue ticket if you think it is ready for grading?

**Comment by ldunne-matc** [comment]
Yes, I will send in week 10 - week 12 Monday night. Thank you!
________________________________

**Comment by cethenmc** [comment]
These week 9 corrections can still be corrected by Thursday night.  You can also hand weeks 12, 13, and 14 until Thursday night.  However, your priority should be to do the whole final project first.  It is worth much more value.

**Comment by ldunne-matc** [comment]
Thank you! I am working on other assignments and finals at this very moment, but I have already started on the python final! I will work on that as soon as possible!

**Comment by cethenmc** [comment]
The only new changes in here to check off some of the check boxes seem to be the description and Author, and the line that says you tested to see it working as expected.  Those two were accomplished but the rest of the checkboxes remain at large.  Adding one more point to the previous score and closing the ticket, as time on the semester has expired.
